name: run-local-gitleaks

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Local Gitleaks Binary
        run: |
          # Ensure the binary 'gitleaks' is in the PATH and can be executed directly
          # run gitleaks, saving SARIF output to temp file
          bash -s << 'EOF'
          #!/bin/bash          
          export TMPSARIF=$(mktemp).sarif
          gitleaks detect -f sarif -r $TMPSARIF
          jq .runs[0].results $TMPSARIF > /tmp/output.sarif
          EOF
        continue-on-error: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gitleaks-output
          path: /tmp/output.sarif 
