name: test-api
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Test API
        run: |
          bash -s << 'EOF'
          curl -L -o /tmp/runs.json \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs
          cat /tmp/runs.json
          EOF
        continue-on-error: true

#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: gitleaks-output
#          path: /tmp/output.json
          artifact_name: gitleaks-output
